<a href="https://colab.research.google.com/github/Solomonkubi/WineQT/blob/main/Python_training.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **DW Live Session 2**

### **1. Data Assesenment**

In [1]:
import pandas as pd
import numpy as np

# Creating a deliberately messy dataset with correct lengths
data = {
    'Name': [
        'John Doe', 'john doe', ' John Doe ', 'John Doe', 'Jane SMITH',
        'Jane Smith', 'JANE SMITH', 'Jack Brown', 'jack brown', 'Sam Wilson',
        'Sam Wilson', np.nan, 'John Doe', 'John Doe', 'Jane Smith'
    ],
    'Age': [
        '28', 'Thirty-two', 45, 'NaN', 33, 36, '29', 40, 'forty-one', np.nan,
        60, 30, '28', '30', 'unknown'
    ],
    'Date Joined': [
        '2020-01-15', '2021-02-20', '2019-03-10', '2020-01-01', '2020-04-25',
        '2020-03-15', '2020-02-25', '2019-10-02', '2018-11-11', '2021-01-15',
        np.nan, '2020-06-15', '2019-07-01', '2020-06-15', '2019-03-10'
    ],
    'Salary': [
        '50000', '60000', '75000', 'Eighty Thousand', 52000, 75000, 100000,
        '85000', '90K', 'None', 110000, 88000, 'Sixty Thousand', 102000, '70,000'
    ],
    'Remarks': [
        'Good employee', 'N/A', 'Excellent', 'GOOD Employee', 'n/a',
        '', 'Great!', 'Needs improvement', 'none', None,
        'Fair', 'excellent', 'Fair', '', 'Promising'
    ]
}

# Convert to DataFrame
df = pd.DataFrame(data)

df

          Name         Age Date Joined           Salary            Remarks
0     John Doe          28  2020-01-15            50000      Good employee
1     john doe  Thirty-two  2021-02-20            60000                N/A
2    John Doe           45  2019-03-10            75000          Excellent
3     John Doe         NaN  2020-01-01  Eighty Thousand      GOOD Employee
4   Jane SMITH          33  2020-04-25            52000                n/a
5   Jane Smith          36  2020-03-15            75000
6   JANE SMITH          29  2020-02-25           100000             Great!
7   Jack Brown          40  2019-10-02            85000  Needs improvement
8   jack brown   forty-one  2018-11-11              90K               none
9   Sam Wilson         NaN  2021-01-15             None               None
10  Sam Wilson          60         NaN           110000               Fair
11         NaN          30  2020-06-15            88000          excellent
12    John Doe          28  2019-07-01   Sixty Thousand               Fair
13    John Doe          30  2020-06-15           102000
14  Jane Smith     unknown  2019-03-10           70,000          Promising

In [3]:
# Duplicating some rows intentionally to check for duplicates
df = pd.concat([df, df.iloc[2:4]], ignore_index=True)
df

          Name         Age Date Joined           Salary            Remarks
0     John Doe          28  2020-01-15            50000      Good employee
1     john doe  Thirty-two  2021-02-20            60000                N/A
2    John Doe           45  2019-03-10            75000          Excellent
3     John Doe         NaN  2020-01-01  Eighty Thousand      GOOD Employee
4   Jane SMITH          33  2020-04-25            52000                n/a
5   Jane Smith          36  2020-03-15            75000
6   JANE SMITH          29  2020-02-25           100000             Great!
7   Jack Brown          40  2019-10-02            85000  Needs improvement
8   jack brown   forty-one  2018-11-11              90K               none
9   Sam Wilson         NaN  2021-01-15             None               None
10  Sam Wilson          60         NaN           110000               Fair
11         NaN          30  2020-06-15            88000          excellent
12    John Doe          28  2019-07-01   Sixty Thousand               Fair
13    John Doe          30  2020-06-15           102000
14  Jane Smith     unknown  2019-03-10           70,000          Promising
15   John Doe           45  2019-03-10            75000          Excellent
16    John Doe         NaN  2020-01-01  Eighty Thousand      GOOD Employee

In [4]:
 df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17 entries, 0 to 16
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Name         16 non-null     object
 1   Age          16 non-null     object
 2   Date Joined  16 non-null     object
 3   Salary       17 non-null     object
 4   Remarks      16 non-null     object
dtypes: object(5)
memory usage: 812.0+ bytes

In [8]:
# Check the first rows of the DataFrame
print("📌 First rows of the DataFrame:")
print(df.head(), "\n")

📌 First rows of the DataFrame:
         Name         Age Date Joined           Salary        Remarks
0    John Doe          28  2020-01-15            50000  Good employee
1    john doe  Thirty-two  2021-02-20            60000            N/A
2   John Doe           45  2019-03-10            75000      Excellent
3    John Doe         NaN  2020-01-01  Eighty Thousand  GOOD Employee
4  Jane SMITH          33  2020-04-25            52000            n/a

In [9]:
# Check the number of rows and columns in the DataFrame
print("📌 Shape of the DataFrame (Rows, Columns):", df.shape, "\n")

📌 Shape of the DataFrame (Rows, Columns): (17, 5)

In [ ]:
# Check the data types of each column
print("📌 Data Types of Each Column:")
print(df.dtypes, "\n")

📌 Data Types of Each Column:
Name           object
Age            object
Date Joined    object
Salary         object
Remarks        object
dtype: object

In [ ]:
# Check the number of missing values in the DataFrame
print("📌 Missing Values Count:")
print(df.isnull().sum(), "\n")

📌 Missing Values Count:
Name           1
Age            1
Date Joined    1
Salary         0
Remarks        1
dtype: int64

In [ ]:
# Check how many duplicated rows are in the DataFrame
print("📌 Number of Duplicate Rows:", df.duplicated().sum(), "\n")

📌 Number of Duplicate Rows: 2

In [ ]:
# Check inconsistencies in the unique values of Salary Column
print("📌 Unique Values in 'Salary' Column:")
print(df['Salary'].unique(), "\n")

📌 Unique Values in 'Salary' Column:
['50000' '60000' '75000' 'Eighty Thousand' 52000 75000 100000 '85000'
 '90K' 'None' 110000 88000 'Sixty Thousand' 102000 '70,000']

In [ ]:
# Check unique values in 'Remarks' column to identify inconsistencies
print("📌 Unique Values in 'Remarks' Column:")
print(df['Remarks'].unique(), "\n")

📌 Unique Values in 'Remarks' Column:
['Good employee' 'N/A' 'Excellent' 'GOOD Employee' 'n/a' '' 'Great!'
 'Needs improvement' 'none' None 'Fair' 'excellent' 'Promising']

In [ ]:
# Check inconsistent capitalization & extra spaces in 'Name' column
print("📌 Unique Values in 'Name' Column (Check for inconsistencies):")
print(df['Name'].unique(), "\n")

📌 Unique Values in 'Name' Column (Check for inconsistencies):
['John Doe' 'john doe' ' John Doe ' 'Jane SMITH' 'Jane Smith' 'JANE SMITH'
 'Jack Brown' 'jack brown' 'Sam Wilson' nan]

In [ ]:
# Check inconsistent Age values (should be numeric)
invalid_ages = df[~df['Age'].astype(str).str.replace('NaN', '').str.isnumeric()]
print("📌 Invalid Age Values (Non-Numeric):")
print(invalid_ages[['Name', 'Age']], "\n")

📌 Invalid Age Values (Non-Numeric):
          Name         Age
1     john doe  Thirty-two
3     John Doe         NaN
8   jack brown   forty-one
9   Sam Wilson         NaN
14  Jane Smith     unknown
16    John Doe         NaN

In [ ]:
# Check for inconsistent date formats
print("📌 Unique Date Formats in 'Date Joined':")
print(df['Date Joined'].unique(), "\n")

📌 Unique Date Formats in 'Date Joined':
['2020-01-15' '2021-02-20' '2019-03-10' '2020-01-01' '2020-04-25'
 '2020-03-15' '2020-02-25' '2019-10-02' '2018-11-11' '2021-01-15' nan
 '2020-06-15' '2019-07-01']

### **2. Data Cleaning**

In [ ]:
df.isnull().sum()

Name           1
Age            1
Date Joined    1
Salary         0
Remarks        1
dtype: int64

In [ ]:
df.dropna(inplace=True)
# also you might want to impute them with fillna()

In [ ]:
df.isna().sum()

Name           0
Age            0
Date Joined    0
Salary         0
Remarks        0
dtype: int64

In [ ]:
df['Name']

0       John Doe
1       john doe
2      John Doe
3       John Doe
4     Jane SMITH
5     Jane Smith
6     JANE SMITH
7     Jack Brown
8     jack brown
12      John Doe
13      John Doe
14    Jane Smith
15     John Doe
16      John Doe
Name: Name, dtype: object

In [ ]:
# Standardize Name (Remove spaces & fix capitalization)
df['Name'] = df['Name'].str.strip().str.title()
df['Name']

0       John Doe
1       John Doe
2       John Doe
3       John Doe
4     Jane Smith
5     Jane Smith
6     Jane Smith
7     Jack Brown
8     Jack Brown
12      John Doe
13      John Doe
14    Jane Smith
15      John Doe
16      John Doe
Name: Name, dtype: object

In [ ]:
df['Age'].dtype

dtype('O')

In [ ]:
# Convert Age to numeric (Invalid values become NaN)
df['Age'] = pd.to_numeric(df['Age'], errors='coerce')
df['Age'].dtype

dtype('float64')

In [ ]:
df['Age']

0     28.0
1      NaN
2     45.0
3      NaN
4     33.0
5     36.0
6     29.0
7     40.0
8      NaN
12    28.0
13    30.0
14     NaN
15    45.0
16     NaN
Name: Age, dtype: float64

In [ ]:
df['Salary'].unique()

array(['50000', '60000', '75000', 'Eighty Thousand', 52000, 75000, 100000,
       '85000', '90K', 'Sixty Thousand', 102000, '70,000'], dtype=object)

In [11]:
 df['Salary'].dtype

dtype('O')

In [12]:
# Fix Salary
df['Salary'] = df['Salary'].replace({
    'Eighty Thousand': 80000, 'Sixty Thousand': 60000, '90K': 90000, '70,000': 70000})

df['Salary'] = pd.to_numeric(df['Salary'], errors='coerce')
print(df['Salary'].dtype)
df['Salary'].head()

float64

0    50000.0
1    60000.0
2    75000.0
3    80000.0
4    52000.0
Name: Salary, dtype: float64

In [ ]:
df['Remarks']

0         Good employee
1                   N/A
2             Excellent
3         GOOD Employee
4                   n/a
5
6                Great!
7     Needs improvement
8                  none
12                 Fair
13
14            Promising
15            Excellent
16        GOOD Employee
Name: Remarks, dtype: object

In [ ]:
# Standardize Remarks
df['Remarks'] = df['Remarks'].str.lower().replace({'n/a': 'unknown', 'none': 'unknown', '': 'unknown'})
df['Remarks']

0         good employee
1               unknown
2             excellent
3         good employee
4               unknown
5               unknown
6                great!
7     needs improvement
8               unknown
12                 fair
13              unknown
14            promising
15            excellent
16        good employee
Name: Remarks, dtype: object

In [ ]:
df['Date Joined'].dtype

dtype('O')

In [ ]:
# Convert Date Joined to datetime format
df['Date Joined'] = pd.to_datetime(df['Date Joined'], errors='coerce')
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 14 entries, 0 to 16
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Name         14 non-null     object
 1   Age          9 non-null      float64
 2   Date Joined  14 non-null     datetime64[ns]
 3   Salary       14 non-null     int64
 4   Remarks      14 non-null     object
dtypes: datetime64[ns](1), float64(1), int64(1), object(2)
memory usage: 672.0+ bytes

In [ ]:
# Remove duplicate rows
df = df.drop_duplicates()
df.duplicated().sum()

np.int64(0)

In [ ]:
#  Print cleaned DataFrame
print(df.head())

         Name   Age Date Joined  Salary        Remarks
0    John Doe  28.0  2020-01-15   50000  good employee
1    John Doe   NaN  2021-02-20   60000        unknown
2    John Doe  45.0  2019-03-10   75000      excellent
3    John Doe   NaN  2020-01-01   80000  good employee
4  Jane Smith  33.0  2020-04-25   52000        unknown

In [ ]:
# Convert column to datetime format, keeping NaT values for invalid/missing dates
df['Date Joined'] = pd.to_datetime(df['Date Joined'], errors='coerce', dayfirst=False)

# Standardize format to YYYY-MM-DD (this keeps NaT values intact)
df['Date Joined'] = df['Date Joined'].dt.strftime('%Y-%m-%d')

print(df)

          Name   Age Date Joined  Salary            Remarks
0     John Doe  28.0  2020-01-15   50000      good employee
1     John Doe   NaN  2021-02-20   60000            unknown
2     John Doe  45.0  2019-03-10   75000          excellent
3     John Doe   NaN  2020-01-01   80000      good employee
4   Jane Smith  33.0  2020-04-25   52000            unknown
5   Jane Smith  36.0  2020-03-15   75000            unknown
6   Jane Smith  29.0  2020-02-25  100000             great!
7   Jack Brown  40.0  2019-10-02   85000  needs improvement
8   Jack Brown   NaN  2018-11-11   90000            unknown
12    John Doe  28.0  2019-07-01   60000               fair
13    John Doe  30.0  2020-06-15  102000            unknown
14  Jane Smith   NaN  2019-03-10   70000          promising

<ipython-input-29-cb13dbb597bf>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Date Joined'] = pd.to_datetime(df['Date Joined'], errors='coerce', dayfirst=False)
<ipython-input-29-cb13dbb597bf>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Date Joined'] = df['Date Joined'].dt.strftime('%Y-%m-%d')

### **3. Data Cleaning: Strings**

In [ ]:
## Applying String Methods to a List of Strings

# Sample list of strings
strings = ["  Hello World  ", "Python Programming", "12345", "hello123", "   ", "UPPER lower"]
strings

['  Hello World  ',
 'Python Programming',
 '12345',
 'hello123',
 '   ',
 'UPPER lower']

In [ ]:
# strip() - Removes leading and trailing whitespace
print([s.strip() for s in strings])

['Hello World', 'Python Programming', '12345', 'hello123', '', 'UPPER lower']

In [ ]:
# lower() - Converts all characters to lowercase
print([s.lower() for s in strings])

['  hello world  ', 'python programming', '12345', 'hello123', '   ', 'upper lower']

In [ ]:
# upper() - Converts all characters to uppercase
print([s.upper() for s in strings])

['  HELLO WORLD  ', 'PYTHON PROGRAMMING', '12345', 'HELLO123', '   ', 'UPPER LOWER']

In [ ]:
# replace() - Replaces occurrences of 'o' with '*'
print([s.replace("o", "*") for s in strings])

['  Hell* W*rld  ', 'Pyth*n Pr*gramming', '12345', 'hell*123', '   ', 'UPPER l*wer']

In [ ]:
# split() - Splits strings by space
print([s.split(" ") for s in strings])

[['', '', 'Hello', 'World', '', ''], ['Python', 'Programming'], ['12345'], ['hello123'], ['', '', '', ''], ['UPPER', 'lower']]

In [ ]:
# join() - Joins a list of words into a single string
print(["-".join(s.split()) for s in strings])

In [ ]:
# find() - Finds the index of 'o'
print([s.find("o") for s in strings])

In [ ]:
# count() - Counts occurrences of 'o'
print([s.count("o") for s in strings])

In [ ]:
# startswith() - Checks if strings start with 'H'
print([s.startswith("H") for s in strings])

In [ ]:

# endswith() - Checks if strings end with 'd'
print([s.endswith("d") for s in strings])

In [ ]:

# format() - Formats a string
print(["This is: {}".format(s) for s in strings])

In [ ]:
# isalpha() - Checks if strings contain only letters
print([s.isalpha() for s in strings])

In [ ]:
# isdigit() - Checks if strings contain only digits
print([s.isdigit() for s in strings])

In [ ]:
# isalnum() - Checks if strings contain only alphanumeric characters
print([s.isalnum() for s in strings])

In [ ]:
# isspace() - Checks if strings contain only whitespace
print([s.isspace() for s in strings])

In [ ]:
# title() - Converts strings to title case
print([s.title() for s in strings])

In [ ]:
# capitalize() - Capitalizes first letter of string
print([s.capitalize() for s in strings])

In [ ]:
# swapcase() - Swaps upper/lower case characters
print([s.swapcase() for s in strings])

In [ ]:
# zfill(10) - Pads numeric strings with zeros
print([s.zfill(10) for s in strings])

In [ ]:
# rjust(15) - Right-justifies strings
print([s.rjust(15) for s in strings])

In [ ]:
# ljust(15) - Left-justifies strings
print([s.ljust(15) for s in strings])